version: '3'

services:
  backend:
    build: ./backend
    # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: /start-reload.sh

    volumes:
      - ./backend/app:/app/
    ports:
      - 80:80
    